package com.googlecode.contraildb.cvm.wrapper;

import com.contrail.cvm.wrapper.model.ClassItem;

import javax.swing.DefaultComboBoxModel;
import org.apache.bcel.classfile.JavaClass;

public class ClassItemProperties extends javax.swing.JPanel
{

    public static final long serialVersionUID = 8732921873l;

    /** Creates new form ClassItemProperties */
    public ClassItemProperties()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        p_Text_Package = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        p_Text_ClassName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        p_List_Functions = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        p_List_Fields = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        p_Text_SuperClass = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        p_Flag_Public = new javax.swing.JCheckBox();
        p_Flag_Final = new javax.swing.JCheckBox();
        p_Flag_Super = new javax.swing.JCheckBox();
        p_Flag_Interface = new javax.swing.JCheckBox();
        p_Flag_Abstract = new javax.swing.JCheckBox();
        p_Flag_StrictFP = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        p_List_Interfaces = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        p_Text_CompilerVersion = new javax.swing.JTextField();

        jLabel1.setText("Package:");

        p_Text_Package.setEditable(false);
        p_Text_Package.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jLabel2.setText("Class name:");

        p_Text_ClassName.setEditable(false);
        p_Text_ClassName.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Methods"));

        p_List_Functions.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        p_List_Functions.setEnabled(false);
        jScrollPane1.setViewportView(p_List_Functions);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fields"));

        p_List_Fields.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        p_List_Fields.setEnabled(false);
        jScrollPane2.setViewportView(p_List_Fields);

        jLabel3.setText("Superclass:");

        p_Text_SuperClass.setEditable(false);
        p_Text_SuperClass.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Visibility"));

        p_Flag_Public.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        p_Flag_Public.setText("Public");
        p_Flag_Public.setEnabled(false);

        p_Flag_Final.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        p_Flag_Final.setText("Final");
        p_Flag_Final.setEnabled(false);

        p_Flag_Super.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        p_Flag_Super.setText("Super");
        p_Flag_Super.setEnabled(false);

        p_Flag_Interface.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        p_Flag_Interface.setText("Interface");
        p_Flag_Interface.setEnabled(false);

        p_Flag_Abstract.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        p_Flag_Abstract.setText("Abstract");
        p_Flag_Abstract.setEnabled(false);

        p_Flag_StrictFP.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        p_Flag_StrictFP.setText("StrictFP");
        p_Flag_StrictFP.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_Flag_Public)
                    .addComponent(p_Flag_Super)
                    .addComponent(p_Flag_Abstract))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p_Flag_Final)
                    .addComponent(p_Flag_Interface)
                    .addComponent(p_Flag_StrictFP))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_Flag_Public)
                    .addComponent(p_Flag_Final))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_Flag_Super)
                    .addComponent(p_Flag_Interface))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_Flag_Abstract)
                    .addComponent(p_Flag_StrictFP))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Implements interfaces"));

        p_List_Interfaces.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        p_List_Interfaces.setEnabled(false);
        jScrollPane3.setViewportView(p_List_Interfaces);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel4.setText("Compiler version:");

        p_Text_CompilerVersion.setEditable(false);
        p_Text_CompilerVersion.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(p_Text_Package, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p_Text_CompilerVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(p_Text_ClassName, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addComponent(p_Text_SuperClass, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_Text_Package, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(p_Text_CompilerVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_Text_ClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p_Text_SuperClass)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox p_Flag_Abstract;
    private javax.swing.JCheckBox p_Flag_Final;
    private javax.swing.JCheckBox p_Flag_Interface;
    private javax.swing.JCheckBox p_Flag_Public;
    private javax.swing.JCheckBox p_Flag_StrictFP;
    private javax.swing.JCheckBox p_Flag_Super;
    private javax.swing.JList p_List_Fields;
    private javax.swing.JList p_List_Functions;
    private javax.swing.JList p_List_Interfaces;
    private javax.swing.JTextField p_Text_ClassName;
    private javax.swing.JTextField p_Text_CompilerVersion;
    private javax.swing.JTextField p_Text_Package;
    private javax.swing.JTextField p_Text_SuperClass;
    // End of variables declaration//GEN-END:variables

    public void setModel(ClassItem _classItem)
    {
        p_Flag_Abstract.setSelected(false);
        p_Flag_Final.setSelected(false);
        p_Flag_Interface.setSelected(false);
        p_Flag_Public.setSelected(false);
        p_Flag_Super.setSelected(false);
        p_Flag_StrictFP.setSelected(false);

        p_Text_ClassName.setText("");
        p_Text_CompilerVersion.setText("");
        p_Text_Package.setText("");
        p_Text_SuperClass.setText("");

        p_List_Interfaces.removeAll();
        p_List_Functions.removeAll();
        p_List_Fields.removeAll();

        if (_classItem != null)
        {
            JavaClass p_class = _classItem.getJavaClass();
            p_Flag_Abstract.setSelected(p_class.isAbstract());
            p_Flag_Final.setSelected(p_class.isFinal());
            p_Flag_Interface.setSelected(p_class.isInterface());
            p_Flag_Public.setSelected(p_class.isPublic());
            p_Flag_Super.setSelected(p_class.isSuper());
            p_Flag_StrictFP.setSelected(p_class.isStrictfp());


            p_List_Fields.setModel(new DefaultComboBoxModel(p_class.getFields()));
            p_List_Functions.setModel(new DefaultComboBoxModel(p_class.getMethods()));
            p_List_Interfaces.setModel(new DefaultComboBoxModel(p_class.getInterfaceNames()));


            p_Text_CompilerVersion.setText(p_class.getMajor()+"."+p_class.getMinor());
            p_Text_ClassName.setText(p_class.getClassName());
            p_Text_SuperClass.setText(p_class.getSuperclassName());
            p_Text_Package.setText(p_class.getPackageName());
        }

    }
}
